/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as GatedRouteImport } from './routes/_gated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadReceiptRouteImport } from './routes/api/upload-receipt'
import { Route as GatedTransactionsRouteImport } from './routes/_gated.transactions'
import { Route as GatedSubscriptionsRouteImport } from './routes/_gated.subscriptions'
import { Route as GatedSettingsRouteImport } from './routes/_gated.settings'
import { Route as GatedRemindersRouteImport } from './routes/_gated.reminders'
import { Route as GatedNetworthRouteImport } from './routes/_gated.networth'
import { Route as GatedMoreRouteImport } from './routes/_gated.more'
import { Route as GatedMonthlyExpensesRouteImport } from './routes/_gated.monthly-expenses'
import { Route as GatedIncomeRouteImport } from './routes/_gated.income'
import { Route as GatedHomeRouteImport } from './routes/_gated.home'
import { Route as GatedGoalsRouteImport } from './routes/_gated.goals'
import { Route as GatedFxRouteImport } from './routes/_gated.fx'
import { Route as GatedDebtsRouteImport } from './routes/_gated.debts'
import { Route as GatedDashboardRouteImport } from './routes/_gated.dashboard'
import { Route as GatedConstantsRouteImport } from './routes/_gated.constants'
import { Route as GatedCategoriesRouteImport } from './routes/_gated.categories'
import { Route as GatedBudgetRouteImport } from './routes/_gated.budget'
import { Route as GatedAccountsRouteImport } from './routes/_gated.accounts'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const GatedRoute = GatedRouteImport.update({
  id: '/_gated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadReceiptRoute = ApiUploadReceiptRouteImport.update({
  id: '/api/upload-receipt',
  path: '/api/upload-receipt',
  getParentRoute: () => rootRouteImport,
} as any)
const GatedTransactionsRoute = GatedTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => GatedRoute,
} as any)
const GatedSubscriptionsRoute = GatedSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => GatedRoute,
} as any)
const GatedSettingsRoute = GatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => GatedRoute,
} as any)
const GatedRemindersRoute = GatedRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => GatedRoute,
} as any)
const GatedNetworthRoute = GatedNetworthRouteImport.update({
  id: '/networth',
  path: '/networth',
  getParentRoute: () => GatedRoute,
} as any)
const GatedMoreRoute = GatedMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => GatedRoute,
} as any)
const GatedMonthlyExpensesRoute = GatedMonthlyExpensesRouteImport.update({
  id: '/monthly-expenses',
  path: '/monthly-expenses',
  getParentRoute: () => GatedRoute,
} as any)
const GatedIncomeRoute = GatedIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => GatedRoute,
} as any)
const GatedHomeRoute = GatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => GatedRoute,
} as any)
const GatedGoalsRoute = GatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => GatedRoute,
} as any)
const GatedFxRoute = GatedFxRouteImport.update({
  id: '/fx',
  path: '/fx',
  getParentRoute: () => GatedRoute,
} as any)
const GatedDebtsRoute = GatedDebtsRouteImport.update({
  id: '/debts',
  path: '/debts',
  getParentRoute: () => GatedRoute,
} as any)
const GatedDashboardRoute = GatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => GatedRoute,
} as any)
const GatedConstantsRoute = GatedConstantsRouteImport.update({
  id: '/constants',
  path: '/constants',
  getParentRoute: () => GatedRoute,
} as any)
const GatedCategoriesRoute = GatedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => GatedRoute,
} as any)
const GatedBudgetRoute = GatedBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => GatedRoute,
} as any)
const GatedAccountsRoute = GatedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => GatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/unlock': typeof UnlockRoute
  '/accounts': typeof GatedAccountsRoute
  '/budget': typeof GatedBudgetRoute
  '/categories': typeof GatedCategoriesRoute
  '/constants': typeof GatedConstantsRoute
  '/dashboard': typeof GatedDashboardRoute
  '/debts': typeof GatedDebtsRoute
  '/fx': typeof GatedFxRoute
  '/goals': typeof GatedGoalsRoute
  '/home': typeof GatedHomeRoute
  '/income': typeof GatedIncomeRoute
  '/monthly-expenses': typeof GatedMonthlyExpensesRoute
  '/more': typeof GatedMoreRoute
  '/networth': typeof GatedNetworthRoute
  '/reminders': typeof GatedRemindersRoute
  '/settings': typeof GatedSettingsRoute
  '/subscriptions': typeof GatedSubscriptionsRoute
  '/transactions': typeof GatedTransactionsRoute
  '/api/upload-receipt': typeof ApiUploadReceiptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/unlock': typeof UnlockRoute
  '/accounts': typeof GatedAccountsRoute
  '/budget': typeof GatedBudgetRoute
  '/categories': typeof GatedCategoriesRoute
  '/constants': typeof GatedConstantsRoute
  '/dashboard': typeof GatedDashboardRoute
  '/debts': typeof GatedDebtsRoute
  '/fx': typeof GatedFxRoute
  '/goals': typeof GatedGoalsRoute
  '/home': typeof GatedHomeRoute
  '/income': typeof GatedIncomeRoute
  '/monthly-expenses': typeof GatedMonthlyExpensesRoute
  '/more': typeof GatedMoreRoute
  '/networth': typeof GatedNetworthRoute
  '/reminders': typeof GatedRemindersRoute
  '/settings': typeof GatedSettingsRoute
  '/subscriptions': typeof GatedSubscriptionsRoute
  '/transactions': typeof GatedTransactionsRoute
  '/api/upload-receipt': typeof ApiUploadReceiptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_gated': typeof GatedRouteWithChildren
  '/unlock': typeof UnlockRoute
  '/_gated/accounts': typeof GatedAccountsRoute
  '/_gated/budget': typeof GatedBudgetRoute
  '/_gated/categories': typeof GatedCategoriesRoute
  '/_gated/constants': typeof GatedConstantsRoute
  '/_gated/dashboard': typeof GatedDashboardRoute
  '/_gated/debts': typeof GatedDebtsRoute
  '/_gated/fx': typeof GatedFxRoute
  '/_gated/goals': typeof GatedGoalsRoute
  '/_gated/home': typeof GatedHomeRoute
  '/_gated/income': typeof GatedIncomeRoute
  '/_gated/monthly-expenses': typeof GatedMonthlyExpensesRoute
  '/_gated/more': typeof GatedMoreRoute
  '/_gated/networth': typeof GatedNetworthRoute
  '/_gated/reminders': typeof GatedRemindersRoute
  '/_gated/settings': typeof GatedSettingsRoute
  '/_gated/subscriptions': typeof GatedSubscriptionsRoute
  '/_gated/transactions': typeof GatedTransactionsRoute
  '/api/upload-receipt': typeof ApiUploadReceiptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/unlock'
    | '/accounts'
    | '/budget'
    | '/categories'
    | '/constants'
    | '/dashboard'
    | '/debts'
    | '/fx'
    | '/goals'
    | '/home'
    | '/income'
    | '/monthly-expenses'
    | '/more'
    | '/networth'
    | '/reminders'
    | '/settings'
    | '/subscriptions'
    | '/transactions'
    | '/api/upload-receipt'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/unlock'
    | '/accounts'
    | '/budget'
    | '/categories'
    | '/constants'
    | '/dashboard'
    | '/debts'
    | '/fx'
    | '/goals'
    | '/home'
    | '/income'
    | '/monthly-expenses'
    | '/more'
    | '/networth'
    | '/reminders'
    | '/settings'
    | '/subscriptions'
    | '/transactions'
    | '/api/upload-receipt'
  id:
    | '__root__'
    | '/'
    | '/_gated'
    | '/unlock'
    | '/_gated/accounts'
    | '/_gated/budget'
    | '/_gated/categories'
    | '/_gated/constants'
    | '/_gated/dashboard'
    | '/_gated/debts'
    | '/_gated/fx'
    | '/_gated/goals'
    | '/_gated/home'
    | '/_gated/income'
    | '/_gated/monthly-expenses'
    | '/_gated/more'
    | '/_gated/networth'
    | '/_gated/reminders'
    | '/_gated/settings'
    | '/_gated/subscriptions'
    | '/_gated/transactions'
    | '/api/upload-receipt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GatedRoute: typeof GatedRouteWithChildren
  UnlockRoute: typeof UnlockRoute
  ApiUploadReceiptRoute: typeof ApiUploadReceiptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_gated': {
      id: '/_gated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload-receipt': {
      id: '/api/upload-receipt'
      path: '/api/upload-receipt'
      fullPath: '/api/upload-receipt'
      preLoaderRoute: typeof ApiUploadReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_gated/transactions': {
      id: '/_gated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof GatedTransactionsRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/subscriptions': {
      id: '/_gated/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof GatedSubscriptionsRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/settings': {
      id: '/_gated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof GatedSettingsRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/reminders': {
      id: '/_gated/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof GatedRemindersRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/networth': {
      id: '/_gated/networth'
      path: '/networth'
      fullPath: '/networth'
      preLoaderRoute: typeof GatedNetworthRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/more': {
      id: '/_gated/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof GatedMoreRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/monthly-expenses': {
      id: '/_gated/monthly-expenses'
      path: '/monthly-expenses'
      fullPath: '/monthly-expenses'
      preLoaderRoute: typeof GatedMonthlyExpensesRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/income': {
      id: '/_gated/income'
      path: '/income'
      fullPath: '/income'
      preLoaderRoute: typeof GatedIncomeRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/home': {
      id: '/_gated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof GatedHomeRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/goals': {
      id: '/_gated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GatedGoalsRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/fx': {
      id: '/_gated/fx'
      path: '/fx'
      fullPath: '/fx'
      preLoaderRoute: typeof GatedFxRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/debts': {
      id: '/_gated/debts'
      path: '/debts'
      fullPath: '/debts'
      preLoaderRoute: typeof GatedDebtsRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/dashboard': {
      id: '/_gated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof GatedDashboardRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/constants': {
      id: '/_gated/constants'
      path: '/constants'
      fullPath: '/constants'
      preLoaderRoute: typeof GatedConstantsRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/categories': {
      id: '/_gated/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof GatedCategoriesRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/budget': {
      id: '/_gated/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof GatedBudgetRouteImport
      parentRoute: typeof GatedRoute
    }
    '/_gated/accounts': {
      id: '/_gated/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof GatedAccountsRouteImport
      parentRoute: typeof GatedRoute
    }
  }
}

interface GatedRouteChildren {
  GatedAccountsRoute: typeof GatedAccountsRoute
  GatedBudgetRoute: typeof GatedBudgetRoute
  GatedCategoriesRoute: typeof GatedCategoriesRoute
  GatedConstantsRoute: typeof GatedConstantsRoute
  GatedDashboardRoute: typeof GatedDashboardRoute
  GatedDebtsRoute: typeof GatedDebtsRoute
  GatedFxRoute: typeof GatedFxRoute
  GatedGoalsRoute: typeof GatedGoalsRoute
  GatedHomeRoute: typeof GatedHomeRoute
  GatedIncomeRoute: typeof GatedIncomeRoute
  GatedMonthlyExpensesRoute: typeof GatedMonthlyExpensesRoute
  GatedMoreRoute: typeof GatedMoreRoute
  GatedNetworthRoute: typeof GatedNetworthRoute
  GatedRemindersRoute: typeof GatedRemindersRoute
  GatedSettingsRoute: typeof GatedSettingsRoute
  GatedSubscriptionsRoute: typeof GatedSubscriptionsRoute
  GatedTransactionsRoute: typeof GatedTransactionsRoute
}

const GatedRouteChildren: GatedRouteChildren = {
  GatedAccountsRoute: GatedAccountsRoute,
  GatedBudgetRoute: GatedBudgetRoute,
  GatedCategoriesRoute: GatedCategoriesRoute,
  GatedConstantsRoute: GatedConstantsRoute,
  GatedDashboardRoute: GatedDashboardRoute,
  GatedDebtsRoute: GatedDebtsRoute,
  GatedFxRoute: GatedFxRoute,
  GatedGoalsRoute: GatedGoalsRoute,
  GatedHomeRoute: GatedHomeRoute,
  GatedIncomeRoute: GatedIncomeRoute,
  GatedMonthlyExpensesRoute: GatedMonthlyExpensesRoute,
  GatedMoreRoute: GatedMoreRoute,
  GatedNetworthRoute: GatedNetworthRoute,
  GatedRemindersRoute: GatedRemindersRoute,
  GatedSettingsRoute: GatedSettingsRoute,
  GatedSubscriptionsRoute: GatedSubscriptionsRoute,
  GatedTransactionsRoute: GatedTransactionsRoute,
}

const GatedRouteWithChildren = GatedRoute._addFileChildren(GatedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GatedRoute: GatedRouteWithChildren,
  UnlockRoute: UnlockRoute,
  ApiUploadReceiptRoute: ApiUploadReceiptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
